#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8000:8000
    command: python /code/mysitePetBook/manage.py runserver 0.0.0.0:8000

  redis:
    image: redis

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
       - web
    ports:
       - "80:80"
    #  - "443:443"
   #volumes:
   #   - ./code/static:/static
    links:
       - web:web
