# Generated by Django 2.1.7 on 2019-04-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_species', models.CharField(max_length=20)),
                ('pet_breed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_fname', models.CharField(max_length=50)),
                ('profile_lname', models.CharField(max_length=50)),
                ('profile_bio', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Profile'),
        ),
    ]
